### ISSUE TITLE
truenas-install filters out nvme devices in #get_physical_disks_list()

### ISSUE THREAD

**Issue by jkaa** [truenas/truenas-installer#19]
Assumption: the following code attempts to filter only drives without partitions to list disks as installation target

` 'for _disk in $(ls /dev/sd* /dev/vd* /dev/hd* /dev/xvd* /dev/nvme* 2>/dev/null | grep -v '[0-9]' | sed 's|/dev/||g')' yields only /dev/sda drives`

**ISSUE: All /dev/nvme[0-9]* devices are (most likely unintentionally) removed from the physikal disk list as well - hence no installation possible on such device.**

**Comment by william-gr** [comment]
@jkaa would https://github.com/truenas/truenas-installer/pull/17 solve your issue?

**Comment by jkaa** [comment]
> @jkaa would #17 solve your issue?

Actually yes. As I see there is even more to it to work than just my proposal.
When will PR #17 get merged to master?
