### ISSUE TITLE
hardcoded /cdrom/TrueNAS-SCALE.update virtualmedia 

### ISSUE THREAD

**Issue by MarcHagen** [truenas/truenas-installer#48]
In the script there is a hardcoded /cdrom mount
https://github.com/truenas/truenas-installer/blob/c3936a9a68ce6579b77a87e4d118f405b47cc001/usr/sbin/truenas-install#L871

But some installations are done through virtualmedia of some sort.
In this case the media is at /dev/sr0

**Comment by sonicaj** [comment]
Can you please create a ticket at https://jira.ixsystems.com please ?
Closing this as we use jira for tracking open issues. Thanks!

**Comment by MarcHagen** [comment]
@sonicaj 
https://jira.ixsystems.com/plugins/servlet/mobile#issue/NAS-114951


maybe adding a note or disable issues all together here makes more sense the. ;)
